### ISSUE TITLE
Can we specify the requirements?

### ISSUE THREAD

**Issue by chongguang** [soichih/node-htcondor#6]
Hello,

I'm trying to use your module to control my htcondor jobs, but in my job submit description file I have this line: Requirements = (Arch == "INTEL") || (Arch == "X86_64") && (machine == "grid-client-1")

Can I do the same thing with your module?

Thanks!

**Comment by soichih** [comment]
Yes, you can add it to submit_options like..

```
htcondor.submit({
    universe: "vanilla",
    executable: "test.sh",
    arguments: "hello",
    notification: "never",
    requirements: '(Arch == "INTEL") || (Arch == "X86_64") && (machine == "grid-client-1")',
    shouldtransferfiles: "yes",
    when_to_transfer_output: "ON_EXIT",
    output: "stdout.txt",
    error: "stderr.txt",
    queue: 1
}).then(function(job) {
    //do your things..
});
```

**Comment by chongguang** [comment]
Yes it works, thanks :+1:
